# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build ZMK

on:
  push:
    paths:
      - "zmk_config/**"
  pull_request:
    paths:
      - "zmk_config/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: zmkfirmware/zmk-build-arm:2.4
    strategy:
      fail-fast: false
      matrix:
        include:
          - shield: a_dux_left
            board: nice_nano_v2
          - shield: a_dux_right
            board: nice_nano_v2
          - board: ferris_rev02
            folder: ferris_rev02
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            bootloader/
            modules/
            tools/
            zephyr/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('zmk_config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
        timeout-minutes: 2
        continue-on-error: true
      - name: Initialize workspace (west init)
        run: west init -l zmk_config
      - name: Update modules (west update)
        run: west update
      - name: Export Zephyr CMake package (west zephyr-export)
        run: west zephyr-export
      - name: Prepare variables
        id: variables
        run: |
          if [ -n "${{ matrix.shield }}" ]; then
            SHIELD_ARG="-DSHIELD=${{ matrix.shield }}"
            ARTIFACT_NAME="${{ matrix.shield }}-${{ matrix.board }}-zmk"
          else
            SHIELD_ARG=
            ARTIFACT_NAME="${{ matrix.board }}-zmk"
          fi

          if [ -n "${{ matrix.folder }}" ]; then
            FOLDER_ARG="zmk_config/${{ matrix.folder }}"
          else
            FOLDER_ARG="zmk_config"
          fi

          echo ::set-output name=shield-arg::${SHIELD_ARG}
          echo ::set-output name=artifact-name::${ARTIFACT_NAME}
          echo ::set-output name=folder-arg::${FOLDER_ARG}
      - name: Build (west build)
        run: west build -s zmk/app -b ${{ matrix.board }} -- ${{ steps.variables.outputs.shield-arg }}
          -DZMK_CONFIG="${GITHUB_WORKSPACE}/${{ steps.variables.outputs.folder-arg }}"
      - name: Generated DTS file
        if: always()
        run: cat -n build/zephyr/${{ matrix.board }}.dts.pre.tmp
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.variables.outputs.artifact-name }}
          path: |
            build/zephyr/zmk.hex
            build/zephyr/zmk.uf2
        continue-on-error: true
